version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: medicnex-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - medicnex-network

  medicnex-file2md:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: medicnex-file2md
    restart: unless-stopped
    ports:
      - "8999:8999"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
      - PADDLEOCR_HOME=/app/.paddleocr
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./.paddleocr:/app/.paddleocr
      - ./app:/app/app  # 挂载应用代码以支持热重载
      - ./.env:/app/.env:ro  # 挂载.env文件以支持热重载
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8999/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - medicnex-network

networks:
  medicnex-network:
    driver: bridge

volumes:
  redis_data: 