version: '3.8'

services:
  file2markdown:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AGENT_API_KEYS=dev-test-key-123,prod-key-456
      - VISION_API_KEY=${VISION_API_KEY:-}
      - VISION_API_BASE=${VISION_API_BASE:-https://api.openai.com/v1}
      - VISION_MODEL=${VISION_MODEL:-gpt-4o-mini}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 